create table if not exists public.alumnos_autorizados (
  email text primary key,
  nombre text,
  activo boolean not null default true,
  rol text not null default 'alumno',
  grupo text,
  telefono text,
  estatus text not null default 'activo',
  fecha_inicio date,
  fecha_fin date,
  notas text,
  created_at timestamptz not null default now()
);

create table if not exists public.libros_drive (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text,
  categoria text,
  tamano text,
  drive_file_id text not null unique,
  autor text not null default 'School to Home',
  visible boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.alumnos_autorizados enable row level security;
alter table public.libros_drive enable row level security;

drop policy if exists "alumno puede leer su propio acceso" on public.alumnos_autorizados;
create policy "alumno puede leer su propio acceso"
on public.alumnos_autorizados
for select
to authenticated
using ((auth.jwt() ->> 'email') = email);

drop policy if exists "usuarios activos pueden leer catalogo" on public.libros_drive;
create policy "usuarios activos pueden leer catalogo"
on public.libros_drive
for select
to authenticated
using (
  exists (
    select 1
    from public.alumnos_autorizados a
    where a.email = (auth.jwt() ->> 'email')
      and a.activo = true
  )
);
